### ISSUE TITLE
Delete option sometimes doesn't work as anticipated

### ISSUE THREAD

**Issue by matteosuppo** [drone-plugins/drone-s3-sync#16]
It happens only sometimes that it deletes files that it shouldn't.

For example just today in the logs we had:

```
Uploading "/drone/src/github.com/matteosuppo/reference/public/en/index.html" with Content-Type "text/html; charset=utf-8" and permissions "public-read"
[...]
Removing remote file "reference/en/index.html"
```

where the config was

```
publish:
    s3_sync:
        acl: public-read
        region: "us-east-1"
        bucket: $$S3_BUCKET
        access_key: $$S3_ACCESS
        secret_key: $$S3_SECRET
        source: public
        delete: true
        target: reference
        when:
            branch: master
```
