### ISSUE TITLE
Passing secrets not working as intended

### ISSUE THREAD

**Issue by markharding** [drone-plugins/drone-s3-sync#37]
As per the documentation, we should be able to pass `secrets: [ aws_access_key_id, aws_secret_access_key ]`. The secrets are set.

This results in the following error:

```
Must set access_key, secret_key, and bucket
```

**Comment by bradrydzewski** [comment]
I can confirm secrets are working with this plugin. Please take a look at http://docs.drone.io/secrets-not-working/. I'm happy to help troubleshoot, if you can provide the information mentioned here http://docs.drone.io/secrets-not-working/#still-having-trouble

**Comment by markharding** [comment]
Here is the build
```
deploy:
    image: plugins/s3-sync:latest
    bucket: minds-repo
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    region: us-east-1
    source: public
    target: front/public
    delete: false
    when:
      branch: [ 'master', 'test/codebuild' ]
```

The ecr secrets work fine
