### ISSUE TITLE
Support for CloudFront invalidation with given path.

### ISSUE THREAD

**Issue by skydan** [drone-plugins/drone-s3-sync#43]
Default "*" value for paths is better than nothing, but it'd be nice to have a way to manage it.

**Comment by m00k** [comment]
I also need this feature. It would be great if the plugin would support something like

```yml
cloudfront:
  distribution: 9c5785d3ece6a9cdefa4
  invalidation_paths:
    - "index.html"
    - "somePath/**/*.js"
```
resulting in invalidation of *index.html* and all javascript files under the path *somePath* (while not touching other files).
