### ISSUE TITLE
Support configuring Cache-Control headers per path

### ISSUE THREAD

**Issue by m00k** [drone-plugins/drone-s3-sync#47]
Currently cache headers can be set globally or on a per file type basis. There is however use cases that require configuration per path/filename, where e.g.

```yml
cache_control:
  "*.js": "max-age=31536000"
  "entry.js": "no-cache"
  "assets/**/*.*": "max-age=86400"
```

should result in all ```*.js``` files being cached for a year, everything underneath ```assets/``` for a day and ```entry.js``` not at all.

**Comment by tboerger** [comment]
Have you tried it? Currently it's implementing a glob pattern match, so I guess this already works.

**Comment by m00k** [comment]
Yes, I saw the usage of glob in the source and I tried a couple of configurations before opening the issue, e.g. with a local file system of

```
dist
|
|--bar
|   |--a.js
|   |--b.js
|   |--index.html
|
|--foo
|   |--a.js
|   |--b.js
|   |--index.html
|
|--main.js
|--vendor.js
|--indes.html
```

and a ```drone.yml```

```yml
source: dist
target: /
delete: false
cache_control:
  "foo/*": "max-age=31536000"
  "main.js": "no-cache"
```

I would have expected ```main.js``` and all files in folder ```foo``` to have headers set but no ```Cache-Control``` headers at all were set. Am I missing something?

**Comment by tboerger** [comment]
I would expect that this already works, this should be debugged.

**Comment by m00k** [comment]
Looks like a leading ```*``` is required. I assumed paths to be compared relative to ```source``` directory, but apparently the plugin goes for the full path. So with
```yml
source: dist
target: /
delete: false
cache_control:
  "*/dist/foo/*.js": "max-age=31536000"
  "*/dist/main.js": "no-cache"
```
I got the expected results.
